const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348036399544";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_21_23_10_07_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICAyMjksXG4gICAgICAgIDExLFxuICAgICAgICA4NyxcbiAgICAgICAgNDIsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTgsXG4gICAgICAgIDQzLFxuICAgICAgICA2MSxcbiAgICAgICAgMTExLFxuICAgICAgICAyNCxcbiAgICAgICAgMjI2LFxuICAgICAgICAzMyxcbiAgICAgICAgNjksXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTEsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDk3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDQsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNTAsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjExLFxuICAgICAgICA1OSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDk3LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEyMVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzcsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTMwLFxuICAgICAgICAzNixcbiAgICAgICAgMTk4LFxuICAgICAgICAxNDksXG4gICAgICAgIDE0NyxcbiAgICAgICAgNTIsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjE0LFxuICAgICAgICAxNzIsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTg4LFxuICAgICAgICAxNCxcbiAgICAgICAgNDcsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxODAsXG4gICAgICAgIDg0LFxuICAgICAgICAxNTMsXG4gICAgICAgIDk2LFxuICAgICAgICAxMCxcbiAgICAgICAgNzksXG4gICAgICAgIDg3LFxuICAgICAgICAxMjAsXG4gICAgICAgIDg5LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIzLFxuICAgICAgICAxMTIsXG4gICAgICAgIDQ1LFxuICAgICAgICAyNCxcbiAgICAgICAgMTA4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNixcbiAgICAgICAgNzYsXG4gICAgICAgIDEzMyxcbiAgICAgICAgODcsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjAsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNDIsXG4gICAgICAgIDE0MixcbiAgICAgICAgOCxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgOTAsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxOTcsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMixcbiAgICAgICAgMjAsXG4gICAgICAgIDczLFxuICAgICAgICA5MixcbiAgICAgICAgOTUsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTA0LFxuICAgICAgICAyMyxcbiAgICAgICAgMTkyLFxuICAgICAgICAxOTIsXG4gICAgICAgIDExNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0MixcbiAgICAgICAgMTY5LFxuICAgICAgICAxMDAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgNDQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgNDYsXG4gICAgICAgIDIxNCxcbiAgICAgICAgOTIsXG4gICAgICAgIDg0LFxuICAgICAgICAxNzMsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNjksXG4gICAgICAgIDIxLFxuICAgICAgICAyNDMsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxNTksXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTY1LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE4MCxcbiAgICAgICAgODYsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTc0LFxuICAgICAgICAzNixcbiAgICAgICAgMjMyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMDBcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NCxcbiAgICAgICAgODQsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTM2LFxuICAgICAgICAxNTksXG4gICAgICAgIDI0OSxcbiAgICAgICAgODYsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjQ5LFxuICAgICAgICAxMDcsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNzAsXG4gICAgICAgIDIzLFxuICAgICAgICA0OSxcbiAgICAgICAgMjA1LFxuICAgICAgICAyMjksXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjM4LFxuICAgICAgICAxODYsXG4gICAgICAgIDMxLFxuICAgICAgICAxNjcsXG4gICAgICAgIDU1LFxuICAgICAgICAyMDgsXG4gICAgICAgIDEsXG4gICAgICAgIDk2LFxuICAgICAgICAxNTUsXG4gICAgICAgIDM4LFxuICAgICAgICA0MyxcbiAgICAgICAgMTA4LFxuICAgICAgICAxMDMsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTE4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDk2LFxuICAgICAgICAyOCxcbiAgICAgICAgMTY5LFxuICAgICAgICAxNzQsXG4gICAgICAgIDU1LFxuICAgICAgICAxNjAsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMjEyLFxuICAgICAgICA4NyxcbiAgICAgICAgMTQyLFxuICAgICAgICAxMDIsXG4gICAgICAgIDE5LFxuICAgICAgICA5NixcbiAgICAgICAgMTIwLFxuICAgICAgICA5LFxuICAgICAgICAxMTgsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxNzUsXG4gICAgICAgIDMsXG4gICAgICAgIDg0LFxuICAgICAgICA2OSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxOTQsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTE4LFxuICAgICAgICAzMCxcbiAgICAgICAgMTgzLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTk3LFxuICAgICAgICAzNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgNyxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTIxXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICA0NCxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMzBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDgsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjA5LFxuICAgICAgICAxMzcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjAwLFxuICAgICAgICAxNTMsXG4gICAgICAgIDEzLFxuICAgICAgICAyMDAsXG4gICAgICAgIDUyLFxuICAgICAgICAyNCxcbiAgICAgICAgNzYsXG4gICAgICAgIDIyNCxcbiAgICAgICAgODcsXG4gICAgICAgIDEzMSxcbiAgICAgICAgNjksXG4gICAgICAgIDcsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjM1LFxuICAgICAgICA3LFxuICAgICAgICAxNDYsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjA5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDkxLFxuICAgICAgICAxODEsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMzYsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTE0LFxuICAgICAgICAyMjEsXG4gICAgICAgIDQzLFxuICAgICAgICA5MSxcbiAgICAgICAgNDMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTAsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjM0LFxuICAgICAgICAyMDAsXG4gICAgICAgIDIxLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjMyLFxuICAgICAgICAxNDQsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjEyLFxuICAgICAgICAxNCxcbiAgICAgICAgNjQsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTk4LFxuICAgICAgICA2NyxcbiAgICAgICAgMTIxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDU4LFxuICAgICAgICAxMTYsXG4gICAgICAgIDMxLFxuICAgICAgICAxNDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIyNixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJBVm0wTHRHNS8ydHM3VnUxS1RWNG5iazdvOUlJZ3V4QXpicGhvRUFWWHA4PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgwMzYzOTk1NDRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjVGQ0IwMjgyMkYzRkNDOTVFNkVBRTVGMDJBRjlBRTBGXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyODMzNjE5N1xuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJoT2htcndyQlJJdVByanE2RFA3b3ZRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjYzY2QxOTk2LTVjZDctNGI2NC04NzZlLTUwZTc1MDQyZDhlYlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMjQsXG4gICAgICAxMzksXG4gICAgICAxNDgsXG4gICAgICAyMDMsXG4gICAgICAxMTAsXG4gICAgICA4NCxcbiAgICAgIDExNCxcbiAgICAgIDEwMSxcbiAgICAgIDIyMyxcbiAgICAgIDk3LFxuICAgICAgOTYsXG4gICAgICAxMjAsXG4gICAgICAxNjQsXG4gICAgICAyNDcsXG4gICAgICAxMTksXG4gICAgICA3LFxuICAgICAgMTA4LFxuICAgICAgMTMyLFxuICAgICAgMjgsXG4gICAgICAxNDhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjI4LFxuICAgICAgMjE5LFxuICAgICAgMTQ2LFxuICAgICAgNDgsXG4gICAgICAxMjEsXG4gICAgICAxOTcsXG4gICAgICAxNDYsXG4gICAgICA2NCxcbiAgICAgIDU2LFxuICAgICAgMTcwLFxuICAgICAgMTEsXG4gICAgICAyMDgsXG4gICAgICAyMDMsXG4gICAgICA4MCxcbiAgICAgIDE0LFxuICAgICAgMzQsXG4gICAgICAxNTMsXG4gICAgICAzNSxcbiAgICAgIDQxLFxuICAgICAgMjE4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIk1IWjk4Rk41XCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MDM2Mzk5NTQ0OjIwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiT0xVRklTQVlPIE9MT1lFREUgRElWSU5FIFNPTkdTIE1JTklTVFJZXCIsXG4gICAgXCJsaWRcIjogXCIyMzI0MDI1MjU4ODIwOToyMEBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNNell6KzhERUx1aWtiZ0dHQWdnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIlNxSWtBTGxMcEpEa2pONVY3ODNoamlKeGxLT3c5UW9ON0RjelBVenZ6ams9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiMk9Ha2pkVWttUU5zWkpBSDRydVRrbFhhaDNwNnliZ1pJQU9CRDJrUFVZWkFkMmRlUXRQMjZmUGk0N0xoTVp2Smtsd3c1QkxiMUlyQW15Mk5BcVFKQVE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiTi91QVlKRVFWWkl1RkNUYml4aDVRSjY0SzRxbHhlaVI5ZGc2TDBDNmtsZGxNcDZWQjlxTS9xbC9yYUdyVWxuc2xrZHd1ZzF0Um9WWEdmb0xWa3RRaEE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0ODAzNjM5OTU0NDoyMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAwLFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICA1NSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDU3XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjgzMzYxOTEsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFQVmxcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBWbC5qc29uIjogIntcImtleURhdGFcIjpcImNnTUhET0tvcHloVW9QNDFpQ2NOY1huLzFiUm85YlhIRG1sZi9IY2VvN3M9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTAzOTM5NTkxNixcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI1MTI0NzcwOTkxXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
